### ISSUE TITLE
sporadic error with undefined leads to 500

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-html-pipeline#146]
probably related to auth:

```
https://main--abp-website--adobe.hlx.page/home?code=0.ASYAWht7-jR7h0OUrtLBeN7O4VVjo4MXrdBOhwHpmjAg-GomAPU.AgABAAIAAAD--DLA3VO7QrddgJg7WevrAgDs_wQA9P996UO5qPQFffMLLobTmSoL742Tn6eWUP5gL3QnEyNcKHRXr7B-UicyAITXP8C8_aZu1arRT30smafFlU6QJ3_sCKUlt4KIm5rSlcHplo7Rkk2L9kY5-NHr28m2sZ-APTJ4jgAsx58kUp6GCVaYTuGvA50w4DMVAFW0_cPipf_BT_DAfEiDE5FqCz52bUSsu_blqSlP0qgggiVxkui0FN982N9T4OR5-FHgIxmrxSPbz1WXmdT9ME3_mNKv_18LIWgALiVrnFMSFOcrURkY_Pxg_mAGAQ3xlMsSJfXnYZsEZD_pkptHQs79ly6ei7TT9tuA_qoHo3OUBE8A2znp1rcp7eaEcEzpUXXn8aglaoJoSTn7a8hEBhqIMQz-Q5lsUFxBa2oliWqqrnw-4Z2esBTz0HBifiBXB4KYwOGnoTvagxlrrXH-L_K2DcCusyDXQiSDoc5EQQ33bLU4wNHn9VsB6KpbagL2YZ4XMh7N4VsXc9QnZjn41EA0bvVOJQhQgCyNZpI0yR-tSZz4XOlqV06NCuV84iyh3qQNLt2bUQZPub29AzrPFC_o0y0JSfzRgnz4XgRskKJRc6pN-M6M_fpj6QNg1vgujsm49sbfNpg1rK8QQ6RpdvZ4omP3fwndje-3s_fsASb91FlxGjeCk9SY_mjCI4Rx7a1ZlYkU38gpQZZuYZnUCSAk3kxpbcFolIMnHSUi17J8MY3FfejGZNllKXrcrrbBN6nAshFzZWbPmgwU_8dZ_ODlIFN0Uwp9FEZuXc9LpQwXIQAM3QEr1WhajK6NT5bnADuuyieS7e54bc2MURqiWo80dNePEHZr8z72Y3g&state=eyJhbGciOiJub25lIn0.eyJvd25lciI6ImFkb2JlIiwicmVwbyI6ImFicC13ZWJzaXRlIiwiY29udGVudEJ1c0lkIjoiZmVlOGI0YTY0NTk0MjFhYjBkOGNjNzMxNjZlZjM0NGU4MTY4YjRhNmQ2M2U3YTA1MGY5ZWQ2NGFjYzQiLCJyZXF1ZXN0UGF0aCI6Ii9ob21lIiwicmVxdWVzdEhvc3QiOiJtYWluLS1hYnAtd2Vic2l0ZS0tYWRvYmUuaGx4LnBhZ2UifQ.&session_state=28e7c861-30ac-4df8-aa06-4eec3c14017b
```

**Comment by dominique-pfister** [comment]
Sample error stack:
```
pipeline status: 500 Cannot read properties of null (reading 'client') TypeError: Cannot read properties of null (reading 'client')
  at AuthInfo.redirectToLogin (/var/task/index.js:6951:44)
  at authenticate (/var/task/index.js:4553:14)
  at async htmlPipe (/var/task/index.js:4096:5)
  at async run (/var/task/index.js:74530:18)
  at async /var/task/index.js:75271:18
  at async Runtime.lambdaAdapter [as handler] (/var/task/index.js:10745:22)timestamp:2022-11-10T10:27:46.366Z}
```
